"""Controlled pilot identities, one-use invitations and revocable sessions.

Revision ID: d261a40ce712
Revises: b9134d27c80f

No accounts, memberships or credentials are generated by this migration. Existing
approvals keep NULL authority bindings and are not valid pilot approvals.
"""
from alembic import op
import sqlalchemy as sa

revision = "d261a40ce712"
down_revision = "b9134d27c80f"
branch_labels = None
depends_on = None


def upgrade():
    op.create_table("pilot_tenants",
        sa.Column("tenant_id", sa.String(80), sa.ForeignKey("tenant_policies.tenant_id"), primary_key=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.String(40), nullable=False))
    op.create_table("pilot_memberships",
        sa.Column("tenant_id", sa.String(80), sa.ForeignKey("pilot_tenants.tenant_id"), primary_key=True),
        sa.Column("user_id", sa.String(80), primary_key=True),
        sa.Column("role", sa.String(24), nullable=False),
        sa.Column("expires_at", sa.String(40), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.String(40), nullable=False))
    for name, hash_column in (("pilot_invites", "credential_hash"), ("pilot_sessions", "token_hash")):
        columns = [
            sa.Column("id", sa.String(40), primary_key=True),
            sa.Column("tenant_id", sa.String(80), nullable=False),
            sa.Column("user_id", sa.String(80), nullable=False),
            sa.Column(hash_column, sa.String(64), nullable=False, unique=True),
            sa.Column("auth_version", sa.String(80), nullable=False),
            sa.Column("expires_at", sa.String(40), nullable=False),
            sa.Column("revoked_at", sa.String(40), nullable=True),
            sa.Column("created_at", sa.String(40), nullable=False),
            sa.ForeignKeyConstraint(["tenant_id", "user_id"],
                ["pilot_memberships.tenant_id", "pilot_memberships.user_id"])]
        if name == "pilot_invites":
            columns.append(sa.Column("consumed_at", sa.String(40), nullable=True))
        op.create_table(name, *columns)
        op.create_index(f"ix_{name}_tenant_id", name, ["tenant_id"])
    op.add_column("approvals", sa.Column("approver_auth_version", sa.String(80), nullable=True))
    op.add_column("external_operations", sa.Column("initiator_id", sa.String(80), nullable=True))
    op.add_column("external_operations", sa.Column("initiator_auth_version", sa.String(80), nullable=True))


def downgrade():
    op.drop_column("external_operations", "initiator_auth_version")
    op.drop_column("external_operations", "initiator_id")
    op.drop_column("approvals", "approver_auth_version")
    for name in ("pilot_sessions", "pilot_invites"):
        op.drop_index(f"ix_{name}_tenant_id", table_name=name)
        op.drop_table(name)
    op.drop_table("pilot_memberships")
    op.drop_table("pilot_tenants")
